framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async_priority_low
            Symfony\Component\Notifier\Message\ChatMessage: async_priority_low
            Symfony\Component\Notifier\Message\SmsMessage: async_priority_low

            App\Import\Application\Message\ImportAllocationsMessage: async_priority_high
            App\Statistics\Application\Message\RecomputeScope: async_priority_low
            App\Statistics\Application\Message\ScheduleScope: [async_priority_high, async_priority_low]

when@test:
    framework:
        messenger:
            transports:
                sync: 'sync://'
            routing:
                App\Import\Application\Message\ImportAllocationsMessage: sync
